version: '3.4'

services:
  filc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  db:
    container_name: Filc
    environment:
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "7014:7014"