name: Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ['Test']
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test echo message
        run: echo Deployment in progress
